---
title: "coursework_unit04"
author: "Jeff Washburn"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# from website: https://www.r-bloggers.com/accessing-apis-from-r-and-a-little-r-programming/
#install.packages(c("httr", "jsonlite", "lubridate"))

library(httr)
library(jsonlite)
## 
## Attaching package: 'jsonlite'
## 
## The following object is masked from 'package:utils':
## 
##     View
library(lubridate)
options(stringsAsFactors = FALSE)
```

```{r echo=TRUE}
# Retrieving valid classifiers
url  <- "http://api.epdb.eu"
path <- "eurlex/directory_code"

#Executing an API call with the GET flavor is done using the GET() function.
raw.result <- GET(url = url, path = path)

#Let’s explore what we’ve got back:
names(raw.result)

#If we examine the status code,
raw.result$status_code

#Let’s look at the actual answer or data payload we’ve got back. Let’s just look at the first few elements:
head(raw.result$content)
## [1] 7b 22 30 31 2e 30

#That’s useless, unless you speak Unicode. Let’s translate that into text.
this.raw.content <- rawToChar(raw.result$content)

#Let’s see how large that is in terms of characters:
nchar(this.raw.content)
## [1] 121493

#That’s rather large. Let’s look at the first 100 characters:
substr(this.raw.content, 1, 100)

#So the result is a single character string that contains a JSON file. Let’s tell R to parse it into something R can work with.
this.content <- fromJSON(this.raw.content)

#What did R make out of it?
class(this.content) #it's a list

#it's a large list
length(this.content) 

#the first element
this.content[[1]] 

#the second element
this.content[[2]] 

# So, apparently R makes a list out of it, with one element per classifier. Each element has:
#  - the directory code document classifier
#  - a URL where one can retrieve more details
#  - the number of documents with that classifier
#  - another URL with yet more details

# So, essentially, the result is a list of lists. Lists are not (always) very nice to work with, and lists of lists are usally despicable. Let’s turn it into a data frame:
this.content.df <- do.call(what = "rbind",
                           args = lapply(this.content, as.data.frame))

#What have we got now?
class(this.content.df) #a single data frame
dim(this.content.df)   #with 462 rows and 4 variables

# see contents
head(this.content.df)
```
